# -*- coding: utf-8 -*-
"""2.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1hD5dzPmw8kJfbxyREZskjrpvVB_05saU
"""

!pip -q install gradio requests openai

# =========================================================
# 1) API KEYS - HARDCODED VERSION
# =========================================================

from openai import OpenAI

# USDA FoodData Central API key
# IMPORTANT: Replace "PYZyG81SJfDvafhb47e50TmPVNxhzmcJUIf5BKQm" with your actual FDC API key.
FDC_API_KEY = "PYZyG81SJfDvafhb47e50TmPVNxhzmcJUIf5BKQm"

# LLM API key
# If you do not want to use an LLM, leave this empty: ""
LLM_API_KEY = "sk-L5Nt7wxLfVi46WosA1SSjra3s3VgWvxcj7IJywS2N4oPOl4C"

# LLM provider settings
LLM_BASE_URL = "https://api.gapapi.com/v1"
LLM_MODEL = "deepseek-chat"

if not FDC_API_KEY or FDC_API_KEY == "YOUR_FDC_API_KEY_HERE":
    raise ValueError("Please put your USDA FoodData Central API key inside FDC_API_KEY.")

llm_client = None

if LLM_API_KEY and LLM_API_KEY != "PASTE_YOUR_LLM_API_KEY_HERE":
    llm_client = OpenAI(
        api_key=LLM_API_KEY,
        base_url=LLM_BASE_URL
    )
else:
    print("LLM API key was not provided. The app will use rule-based fallback responses.")

# =========================================================
# AI Nutrition Coach for Google Colab
# Fully English UI, prompts, errors, and outputs
# USDA FoodData Central API for calories, macros, and micronutrients
# API keys are hardcoded inside this code
# =========================================================

import re
import json
import requests
import gradio as gr
from openai import OpenAI


# =========================================================
# 1) HARDCODED API KEYS
# =========================================================

# Put your USDA FoodData Central API key here



# =========================================================
# 2) USDA FOODDATA CENTRAL CLIENT
# =========================================================

FDC_BASE_URL = "https://api.nal.usda.gov/fdc/v1"


class FoodDataCentralClient:
    def __init__(self, api_key):
        self.api_key = api_key

    def search_food(self, query, page_size=5):
        url = f"{FDC_BASE_URL}/foods/search"

        payload = {
            "query": query,
            "pageSize": page_size,
            "dataType": [
                "Foundation",
                "SR Legacy",
                "Survey (FNDDS)",
                "Branded"
            ]
        }

        response = requests.post(
            url,
            params={"api_key": self.api_key},
            json=payload,
            timeout=30
        )

        response.raise_for_status()

        foods = response.json().get("foods", [])

        priority = {
            "Foundation": 1,
            "SR Legacy": 2,
            "Survey (FNDDS)": 3,
            "Branded": 4
        }

        foods = sorted(
            foods,
            key=lambda item: priority.get(item.get("dataType", ""), 99)
        )

        return foods

    def get_food_details(self, fdc_id):
        url = f"{FDC_BASE_URL}/food/{fdc_id}"

        response = requests.get(
            url,
            params={"api_key": self.api_key},
            timeout=30
        )

        response.raise_for_status()
        return response.json()


fdc_client = FoodDataCentralClient(FDC_API_KEY)


# =========================================================
# 3) NUTRIENT EXTRACTION
# =========================================================

NUTRIENT_NUMBER_MAP = {
    "1008": "calories_kcal",
    "1003": "protein_g",
    "1004": "fat_g",
    "1005": "carbohydrates_g",
    "1079": "fiber_g",
    "2000": "sugars_g",
    "1087": "calcium_mg",
    "1089": "iron_mg",
    "1090": "magnesium_mg",
    "1092": "potassium_mg",
    "1093": "sodium_mg",
    "1095": "zinc_mg",
    "1162": "vitamin_c_mg",
    "1114": "vitamin_d_mcg",
    "1178": "vitamin_b12_mcg",
    "1177": "folate_mcg",
    "1190": "folate_dfe_mcg"
}

NUTRIENT_NAME_FALLBACK = {
    "energy": "calories_kcal",
    "protein": "protein_g",
    "total lipid": "fat_g",
    "total fat": "fat_g",
    "carbohydrate": "carbohydrates_g",
    "fiber": "fiber_g",
    "sugars": "sugars_g",
    "calcium": "calcium_mg",
    "iron": "iron_mg",
    "magnesium": "magnesium_mg",
    "potassium": "potassium_mg",
    "sodium": "sodium_mg",
    "zinc": "zinc_mg",
    "vitamin c": "vitamin_c_mg",
    "vitamin d": "vitamin_d_mcg",
    "vitamin b-12": "vitamin_b12_mcg",
    "vitamin b12": "vitamin_b12_mcg",
    "folate": "folate_mcg"
}


def extract_nutrients_per_100g(food_detail):
    nutrients = {}

    for item in food_detail.get("foodNutrients", []):
        nutrient_obj = item.get("nutrient", {})
        nutrient_number = str(nutrient_obj.get("number", "")).strip()
        nutrient_name = str(nutrient_obj.get("name", "")).lower().strip()
        unit_name = str(nutrient_obj.get("unitName", "")).lower().strip()
        amount = item.get("amount")

        if amount is None:
            continue

        key = NUTRIENT_NUMBER_MAP.get(nutrient_number)

        if not key:
            for name_part, mapped_key in NUTRIENT_NAME_FALLBACK.items():
                if name_part in nutrient_name:
                    key = mapped_key
                    break

        # Avoid treating kJ as kcal.
        if key == "calories_kcal" and unit_name not in ["kcal", "calorie", "calories"]:
            continue

        if key and key not in nutrients:
            nutrients[key] = round(float(amount), 2)

    return nutrients


def scale_nutrients(nutrients_per_100g, grams):
    factor = grams / 100.0

    return {
        nutrient: round(value * factor, 2)
        for nutrient, value in nutrients_per_100g.items()
    }


def add_nutrients(total, item):
    for nutrient, value in item.items():
        total[nutrient] = round(total.get(nutrient, 0) + value, 2)

    return total


# =========================================================
# 4) FOOD INPUT PARSER AND MEAL ANALYZER
# =========================================================

def parse_foods_text(text):
    """
    Expected format:
    banana 120g, boiled egg 100g, cooked rice 180g

    USDA works best with English food names.
    """
    if not text:
        return []

    normalized = text.replace("،", ",")
    chunks = [chunk.strip() for chunk in normalized.split(",") if chunk.strip()]

    foods = []

    for chunk in chunks:
        grams = 100.0

        match = re.search(
            r"(\d+(\.\d+)?)\s*(g|gram|grams)",
            chunk,
            flags=re.IGNORECASE
        )

        if match:
            grams = float(match.group(1))
            name = chunk[:match.start()].strip()
        else:
            name = chunk.strip()

        name = re.sub(r"\s+", " ", name).strip()

        if name:
            foods.append({
                "name": name,
                "grams": grams
            })

    return foods


def analyze_one_food(food):
    food_name = food["name"]
    grams = float(food.get("grams", 100))

    search_results = fdc_client.search_food(food_name, page_size=5)

    if not search_results:
        raise ValueError(f"No USDA match found for: {food_name}")

    selected_food = search_results[0]
    fdc_id = selected_food["fdcId"]

    food_detail = fdc_client.get_food_details(fdc_id)

    nutrients_per_100g = extract_nutrients_per_100g(food_detail)
    scaled_nutrients = scale_nutrients(nutrients_per_100g, grams)

    return {
        "input_name": food_name,
        "matched_name": food_detail.get("description", selected_food.get("description")),
        "fdc_id": fdc_id,
        "data_type": food_detail.get("dataType", selected_food.get("dataType")),
        "grams": grams,
        "nutrients": scaled_nutrients
    }


def analyze_meal(foods):
    items = []
    totals = {}
    not_found = []

    for food in foods:
        try:
            analyzed_item = analyze_one_food(food)
            items.append(analyzed_item)
            totals = add_nutrients(totals, analyzed_item["nutrients"])
        except Exception as error:
            not_found.append({
                "food": food.get("name"),
                "error": str(error)
            })

    return {
        "items": items,
        "totals": totals,
        "not_found": not_found
    }


# =========================================================
# 5) BODY AND CALORIE CALCULATIONS
# =========================================================

ACTIVITY_FACTORS = {
    "sedentary": 1.2,
    "light": 1.375,
    "moderate": 1.55,
    "active": 1.725,
    "very_active": 1.9
}


def calculate_bmi(weight_kg, height_cm):
    height_m = height_cm / 100.0
    return round(weight_kg / (height_m ** 2), 1)


def bmi_category(bmi):
    if bmi < 18.5:
        return "underweight"
    if bmi < 25:
        return "normal weight"
    if bmi < 30:
        return "overweight"
    if bmi < 35:
        return "class 1 obesity"
    if bmi < 40:
        return "class 2 obesity"
    return "class 3 obesity"


def calculate_bmr(weight_kg, height_cm, age, gender):
    """
    Mifflin-St Jeor equation.
    gender should be: male, female, or unknown.
    """
    base = 10 * weight_kg + 6.25 * height_cm - 5 * age

    if gender == "male":
        return round(base + 5)

    if gender == "female":
        return round(base - 161)

    return round(base - 78)


def calculate_tdee(bmr, activity_level):
    factor = ACTIVITY_FACTORS.get(activity_level, 1.2)
    return round(bmr * factor)


def calculate_calorie_target(age, bmr, tdee, goal):
    """
    Safety rule:
    For users under 18, the assistant does not recommend a calorie deficit.
    """
    notes = []

    if age < 18:
        notes.append(
            "For users under 18, aggressive calorie restriction, fasting, strict dieting, or meal skipping is not recommended. The focus should be healthy growth, balanced meals, adequate sleep, and safe activity."
        )
        return {
            "target_calories": tdee,
            "strategy": "maintenance_for_growth",
            "notes": notes
        }

    if goal == "lose_weight":
        target = max(bmr, tdee - 350)
        notes.append(
            "A mild calorie deficit was selected, and the target was not set below estimated BMR."
        )
        return {
            "target_calories": round(target),
            "strategy": "mild_deficit",
            "notes": notes
        }

    if goal == "gain_weight":
        return {
            "target_calories": round(tdee + 300),
            "strategy": "mild_surplus",
            "notes": [
                "A mild calorie surplus was selected for gradual weight gain."
            ]
        }

    return {
        "target_calories": tdee,
        "strategy": "maintenance",
        "notes": [
            "The current goal is weight maintenance and improving nutrition quality."
        ]
    }


# =========================================================
# 6) USER ANSWER PARSERS
# =========================================================

def parse_number_answer(text, field_name, min_value=None, max_value=None):
    match = re.search(r"\d+(\.\d+)?", str(text))

    if not match:
        raise ValueError(f"Please enter a valid number for {field_name}.")

    value = float(match.group(0))

    if min_value is not None and value < min_value:
        raise ValueError(f"{field_name} is too low.")

    if max_value is not None and value > max_value:
        raise ValueError(f"{field_name} is too high.")

    return value


def parse_gender(text):
    value = str(text).lower().strip()

    if value in ["1", "male", "man", "boy", "m"]:
        return "male"

    if value in ["2", "female", "woman", "girl", "f"]:
        return "female"

    return "unknown"


def parse_activity(text):
    value = str(text).lower().strip()

    number_map = {
        "1": "sedentary",
        "2": "light",
        "3": "moderate",
        "4": "active",
        "5": "very_active"
    }

    digit = re.search(r"[1-5]", value)
    if digit:
        return number_map[digit.group(0)]

    if "sedentary" in value:
        return "sedentary"
    if "light" in value:
        return "light"
    if "moderate" in value:
        return "moderate"
    if "very" in value:
        return "very_active"
    if "active" in value:
        return "active"

    return "sedentary"


def parse_goal(text):
    value = str(text).lower().strip()

    if "1" in value or "maintain" in value:
        return "maintain"

    if "2" in value or "lose" in value or "fat" in value:
        return "lose_weight"

    if "3" in value or "gain" in value or "muscle" in value:
        return "gain_weight"

    return "maintain"


def parse_conditions(text):
    value = str(text).lower().strip()

    if value in ["none", "no", "nothing", "n/a", "na"]:
        return []

    conditions = []

    condition_keywords = {
        "diabetes": ["diabetes", "blood sugar", "glucose"],
        "hypertension": ["hypertension", "blood pressure", "high pressure"],
        "high_cholesterol": ["cholesterol", "triglyceride", "lipid"],
        "kidney_disease": ["kidney", "renal"],
        "liver_disease": ["liver", "hepatic"],
        "anemia": ["anemia", "iron deficiency"]
    }

    for condition, keywords in condition_keywords.items():
        if any(keyword in value for keyword in keywords):
            conditions.append(condition)

    return conditions


# =========================================================
# 7) RULE-BASED RECOMMENDATIONS
# =========================================================

def build_rule_based_recommendations(profile, body_report, meal_report):
    recommendations = []

    age = profile["age"]
    bmi = body_report["bmi"]
    goal = profile["goal"]
    conditions = profile.get("conditions", [])
    restrictions = profile.get("allergies_or_restrictions", "")

    if age < 18:
        recommendations.append(
            "Because the user is under 18, the focus should be healthy growth, regular meals, enough protein, sleep, and safe physical activity. Strict dieting, fasting, or skipping meals is not recommended."
        )

    if bmi < 18.5:
        recommendations.append(
            "BMI is in the underweight range. Consider improving meal consistency and adding healthy energy sources such as nuts, dairy, eggs, legumes, whole grains, avocado, and olive oil."
        )
    elif bmi >= 25:
        recommendations.append(
            "BMI is above the normal range. It may help to reduce sugary drinks, fast food, fried foods, and high-calorie snacks while increasing vegetables, lean protein, and fiber-rich foods."
        )
    else:
        recommendations.append(
            "BMI is in the normal range. The main focus should be maintaining a balanced intake of protein, carbohydrates, healthy fats, fiber, and micronutrients."
        )

    if "diabetes" in conditions:
        recommendations.append(
            "Because diabetes or blood sugar issues were reported, simple sugars and sugary drinks should be limited, and fiber-rich carbohydrate sources should be prioritized."
        )

    if "hypertension" in conditions:
        recommendations.append(
            "Because hypertension was reported, salty and processed foods such as chips, canned foods, sausages, processed meats, and fast food should be limited."
        )

    if "high_cholesterol" in conditions:
        recommendations.append(
            "For high cholesterol, it may help to reduce saturated fat and fried foods while increasing legumes, vegetables, oats, fish, nuts, and olive oil."
        )

    if "kidney_disease" in conditions:
        recommendations.append(
            "For kidney disease, protein, sodium, potassium, and phosphorus intake should be personalized by a physician or registered dietitian."
        )

    if "liver_disease" in conditions:
        recommendations.append(
            "For liver disease, nutrition advice should be personalized based on medical evaluation and lab results."
        )

    if "anemia" in conditions:
        recommendations.append(
            "For anemia or suspected iron deficiency, iron-rich foods such as lean meat, legumes, eggs, and leafy greens may help, especially when combined with vitamin C sources."
        )

    if restrictions and restrictions.lower() not in ["none", "no", "nothing", "n/a", "na"]:
        recommendations.append(
            f"The reported allergy, restriction, or diet style should be respected when choosing foods: {restrictions}"
        )

    if meal_report and meal_report.get("items"):
        totals = meal_report.get("totals", {})

        if totals.get("fiber_g", 0) < 5:
            recommendations.append(
                "The recorded meal appears low in fiber. Adding vegetables, whole fruit, legumes, or whole grains could improve it."
            )

        if totals.get("protein_g", 0) < 15:
            recommendations.append(
                "The recorded meal appears low in protein. Consider adding eggs, chicken, fish, yogurt, legumes, tofu, or another protein source."
            )

        if totals.get("sodium_mg", 0) > 800:
            recommendations.append(
                "The recorded meal appears relatively high in sodium. Lower-sodium choices may be better for the next meals."
            )

        if totals.get("calories_kcal", 0) < 250:
            recommendations.append(
                "The recorded meal appears quite low in calories. If this was intended to be a main meal, consider adding a balanced source of protein, carbohydrates, and healthy fats."
            )

    if goal == "lose_weight" and age >= 18:
        recommendations.append(
            "For weight loss, a mild calorie deficit, enough protein, higher fiber intake, and regular physical activity are safer than extreme dieting."
        )

    if goal == "gain_weight":
        recommendations.append(
            "For weight gain, a mild calorie surplus with enough protein and resistance training is usually more effective than eating random high-calorie foods."
        )

    return recommendations


# =========================================================
# 8) LLM PROMPTS - ENGLISH ONLY
# =========================================================

SYSTEM_PROMPT = """
You are a careful AI nutrition coaching assistant.

Rules:
- Reply only in English.
- Use only the numeric nutrition data provided in the JSON input.
- Do not invent calories, macros, or micronutrients.
- Do not diagnose diseases.
- Do not claim to replace a physician or registered dietitian.
- If the user is under 18, do not recommend aggressive weight loss, strict dieting, fasting, meal skipping, or very low calorie targets.
- Give practical, moderate, safe nutrition and lifestyle recommendations.
- Mention that USDA food matching may be imperfect.
- Keep the response structured, clear, and useful.
"""

USER_PROMPT_TEMPLATE = """
Create a personalized nutrition coaching report from the JSON data below.

Required English output structure:
1. Short Summary
2. Body Calculations
   - BMI
   - BMR
   - TDEE
   - Suggested calorie target
3. Meal Nutrient Analysis, if foods were provided
4. Main Recommendations
5. Safety Note

Important:
- Do not add numeric values that are not in the JSON.
- Do not give a medical diagnosis.
- Be especially careful if the user is under 18.

JSON data:
{data}
"""


def generate_llm_response(profile, body_report, meal_report, recommendations):
    if not llm_client:
        return None

    payload = {
        "profile": profile,
        "body_report": body_report,
        "meal_report": meal_report,
        "rule_based_recommendations": recommendations
    }

    prompt = USER_PROMPT_TEMPLATE.format(
        data=json.dumps(payload, ensure_ascii=False, indent=2)
    )

    response = llm_client.chat.completions.create(
        model=LLM_MODEL,
        messages=[
            {"role": "system", "content": SYSTEM_PROMPT},
            {"role": "user", "content": prompt}
        ],
        temperature=0.2,
        max_tokens=1300
    )

    return response.choices[0].message.content


# =========================================================
# 9) FALLBACK REPORT WITHOUT LLM
# =========================================================

def fallback_response(profile, body_report, meal_report, recommendations):
    lines = []

    lines.append("## 1. Short Summary")
    lines.append("Based on the information entered, this is an initial nutrition coaching report.")

    lines.append("\n## 2. Body Calculations")
    lines.append(f"- Age: {profile['age']}")
    lines.append(f"- Sex used for BMR calculation: {profile['gender']}")
    lines.append(f"- Height: {profile['height_cm']} cm")
    lines.append(f"- Weight: {profile['weight_kg']} kg")
    lines.append(f"- BMI: {body_report['bmi']} ({body_report['bmi_category']})")
    lines.append(f"- Estimated BMR: {body_report['bmr']} kcal/day")
    lines.append(f"- Estimated TDEE: {body_report['tdee']} kcal/day")
    lines.append(f"- Suggested calorie target: {body_report['calorie_plan']['target_calories']} kcal/day")
    lines.append(f"- Strategy: {body_report['calorie_plan']['strategy']}")

    for note in body_report["calorie_plan"].get("notes", []):
        lines.append(f"- {note}")

    if meal_report and meal_report.get("items"):
        lines.append("\n## 3. Meal Nutrient Analysis")

        for item in meal_report["items"]:
            nutrients = item["nutrients"]

            lines.append(
                f"- Input: {item['input_name']} | "
                f"USDA match: {item['matched_name']} | "
                f"Data type: {item['data_type']} | "
                f"Amount: {item['grams']} g"
            )

            lines.append(
                f"  Calories: {nutrients.get('calories_kcal', 'N/A')} kcal, "
                f"Protein: {nutrients.get('protein_g', 'N/A')} g, "
                f"Carbohydrates: {nutrients.get('carbohydrates_g', 'N/A')} g, "
                f"Fat: {nutrients.get('fat_g', 'N/A')} g"
            )

        totals = meal_report["totals"]

        lines.append("\n### Estimated Meal Total")
        lines.append(f"- Calories: {totals.get('calories_kcal', 'N/A')} kcal")
        lines.append(f"- Protein: {totals.get('protein_g', 'N/A')} g")
        lines.append(f"- Carbohydrates: {totals.get('carbohydrates_g', 'N/A')} g")
        lines.append(f"- Fat: {totals.get('fat_g', 'N/A')} g")
        lines.append(f"- Fiber: {totals.get('fiber_g', 'N/A')} g")
        lines.append(f"- Sugars: {totals.get('sugars_g', 'N/A')} g")
        lines.append(f"- Sodium: {totals.get('sodium_mg', 'N/A')} mg")
        lines.append(f"- Potassium: {totals.get('potassium_mg', 'N/A')} mg")
        lines.append(f"- Calcium: {totals.get('calcium_mg', 'N/A')} mg")
        lines.append(f"- Iron: {totals.get('iron_mg', 'N/A')} mg")
        lines.append(f"- Magnesium: {totals.get('magnesium_mg', 'N/A')} mg")
        lines.append(f"- Zinc: {totals.get('zinc_mg', 'N/A')} mg")
        lines.append(f"- Vitamin C: {totals.get('vitamin_c_mg', 'N/A')} mg")
        lines.append(f"- Vitamin D: {totals.get('vitamin_d_mcg', 'N/A')} mcg")
        lines.append(f"- Vitamin B12: {totals.get('vitamin_b12_mcg', 'N/A')} mcg")
        lines.append(f"- Folate: {totals.get('folate_mcg', 'N/A')} mcg")

    if meal_report and meal_report.get("not_found"):
        lines.append("\n## Foods Not Found")
        for item in meal_report["not_found"]:
            lines.append(f"- {item['food']}: {item['error']}")

    lines.append("\n## 4. Main Recommendations")
    for recommendation in recommendations:
        lines.append(f"- {recommendation}")

    lines.append("\n## 5. Safety Note")
    lines.append(
        "This response is not a replacement for a physician or registered dietitian. USDA food matching may not be perfect, so nutrient values should be treated as estimates."
    )

    return "\n".join(lines)


# =========================================================
# 10) FULL REPORT GENERATOR
# =========================================================

def generate_report(answers):
    age = int(answers["age"])
    gender = answers["gender"]
    height_cm = float(answers["height_cm"])
    weight_kg = float(answers["weight_kg"])
    activity_level = answers["activity_level"]
    goal = answers["goal"]

    profile = {
        "age": age,
        "gender": gender,
        "height_cm": height_cm,
        "weight_kg": weight_kg,
        "activity_level": activity_level,
        "goal": goal,
        "conditions": answers.get("conditions", []),
        "allergies_or_restrictions": answers.get("allergies_or_restrictions", "none"),
        "meal_text": answers.get("meal_text", "")
    }

    bmi = calculate_bmi(weight_kg, height_cm)
    bmr = calculate_bmr(weight_kg, height_cm, age, gender)
    tdee = calculate_tdee(bmr, activity_level)

    body_report = {
        "bmi": bmi,
        "bmi_category": bmi_category(bmi),
        "bmr": bmr,
        "tdee": tdee,
        "calorie_plan": calculate_calorie_target(age, bmr, tdee, goal)
    }

    foods = parse_foods_text(profile["meal_text"])
    meal_report = analyze_meal(foods) if foods else None

    recommendations = build_rule_based_recommendations(
        profile=profile,
        body_report=body_report,
        meal_report=meal_report
    )

    llm_answer = generate_llm_response(
        profile=profile,
        body_report=body_report,
        meal_report=meal_report,
        recommendations=recommendations
    )

    if llm_answer:
        return llm_answer

    return fallback_response(
        profile=profile,
        body_report=body_report,
        meal_report=meal_report,
        recommendations=recommendations
    )


# =========================================================
# 11) CHATBOT QUESTION FLOW
# =========================================================

QUESTIONS = [
    {
        "key": "age",
        "question": "Question 1/9: What is your age? Please enter a number.",
        "parser": lambda text: int(parse_number_answer(text, "age", 5, 120))
    },
    {
        "key": "gender",
        "question": (
            "Question 2/9: What is your biological sex for BMR calculation?\n"
            "Type one option:\n"
            "1) male\n"
            "2) female\n"
            "3) unknown"
        ),
        "parser": parse_gender
    },
    {
        "key": "height_cm",
        "question": "Question 3/9: What is your height in centimeters? Example: 175",
        "parser": lambda text: parse_number_answer(text, "height_cm", 80, 250)
    },
    {
        "key": "weight_kg",
        "question": "Question 4/9: What is your weight in kilograms? Example: 70",
        "parser": lambda text: parse_number_answer(text, "weight_kg", 20, 300)
    },
    {
        "key": "activity_level",
        "question": (
            "Question 5/9: What is your activity level?\n"
            "1) sedentary: little or no exercise\n"
            "2) light: light exercise 1–3 days/week\n"
            "3) moderate: moderate exercise 3–5 days/week\n"
            "4) active: hard exercise 6–7 days/week\n"
            "5) very active: very hard exercise or physical job"
        ),
        "parser": parse_activity
    },
    {
        "key": "goal",
        "question": (
            "Question 6/9: What is your main goal?\n"
            "1) maintain weight\n"
            "2) lose weight\n"
            "3) gain weight or muscle"
        ),
        "parser": parse_goal
    },
    {
        "key": "conditions",
        "question": (
            "Question 7/9: Do you have any relevant health conditions?\n"
            "Examples: none, diabetes, hypertension, high cholesterol, kidney disease, liver disease, anemia"
        ),
        "parser": parse_conditions
    },
    {
        "key": "allergies_or_restrictions",
        "question": (
            "Question 8/9: Do you have any food allergies, food restrictions, or diet style?\n"
            "Examples: none, lactose intolerance, gluten-free, vegetarian, vegan"
        ),
        "parser": lambda text: str(text).strip() or "none"
    },
    {
        "key": "meal_text",
        "question": (
            "Question 9/9: Enter foods to analyze using English food names and grams.\n"
            "Example: banana 120g, boiled egg 100g, cooked rice 180g\n\n"
            "If you do not want meal analysis, type: none"
        ),
        "parser": lambda text: "" if str(text).strip().lower() in ["none", "no", "skip", "n/a", "na"] else str(text).strip()
    }
]


def start_chat():
    state = {
        "step": 0,
        "answers": {}
    }

    history = [
        {
            "role": "assistant",
            "content": (
                "Welcome to the AI Nutrition Coach.\n\n"
                "I will ask a few questions, calculate BMI, BMR, TDEE, estimate a calorie target, "
                "analyze foods with USDA FoodData Central, and generate a personalized nutrition report.\n\n"
                f"{QUESTIONS[0]['question']}"
            )
        }
    ]

    return history, state


def chatbot_reply(user_message, history, state):
    if history is None:
        history = []

    if state is None:
        history, state = start_chat()

    user_message = str(user_message).strip()

    if not user_message:
        return "", history, state

    history.append({
        "role": "user",
        "content": user_message
    })

    step = state["step"]

    if step >= len(QUESTIONS):
        history.append({
            "role": "assistant",
            "content": "The questionnaire is already complete. Click Restart to start again."
        })
        return "", history, state

    current_question = QUESTIONS[step]

    try:
        parsed_answer = current_question["parser"](user_message)
        state["answers"][current_question["key"]] = parsed_answer
        state["step"] += 1

    except Exception as error:
        history.append({
            "role": "assistant",
            "content": (
                f"I could not understand that answer.\n\n"
                f"Error: {str(error)}\n\n"
                f"{current_question['question']}"
            )
        })
        return "", history, state

    if state["step"] < len(QUESTIONS):
        next_question = QUESTIONS[state["step"]]["question"]
        history.append({
            "role": "assistant",
            "content": next_question
        })
        return "", history, state

    history.append({
        "role": "assistant",
        "content": "Thank you. I am generating your nutrition report now."
    })

    try:
        report = generate_report(state["answers"])

    except Exception as error:
        report = (
            "An error occurred while generating the report.\n\n"
            f"Error details: {str(error)}\n\n"
            "For USDA FoodData Central, food names should be entered in English.\n"
            "Example: banana 120g, boiled egg 100g, cooked rice 180g"
        )

    history.append({
        "role": "assistant",
        "content": report
    })

    return "", history, state


# =========================================================
# 12) GRADIO UI
# =========================================================

with gr.Blocks(title="AI Nutrition Coach") as demo:
    gr.Markdown("# AI Nutrition Coach")
    gr.Markdown(
        "This Colab chatbot asks health and lifestyle questions, calculates BMI/BMR/TDEE, "
        "uses USDA FoodData Central for calories and micronutrients, "
        "and generates a personalized nutrition coaching report in English."
    )

    chatbot = gr.Chatbot(
        height=560
    )

    state = gr.State()

    user_input = gr.Textbox(
        label="Your answer",
        placeholder="Type your answer here and press Enter..."
    )

    with gr.Row():
        restart_button = gr.Button("Restart")

    demo.load(
        fn=start_chat,
        inputs=None,
        outputs=[chatbot, state]
    )

    user_input.submit(
        fn=chatbot_reply,
        inputs=[user_input, chatbot, state],
        outputs=[user_input, chatbot, state]
    )

    restart_button.click(
        fn=start_chat,
        inputs=None,
        outputs=[chatbot, state]
    )


demo.launch(share=True, debug=True)